version: '3.3'
services:
  db:
    image: mysql
    container_name: database
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'project'
      MYSQL_PASSWORD: 'test_project123'
      MYSQL_ROOT_PASSWORD: 'root_test_project123'
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
  server:
    build: ./server
    container_name: server
    restart: on-failure
    ports:
    - "4000:4000"
    depends_on:
     - db
    environment:
      WAIT_HOSTS: db:3306
  client:
   build: ./client
   container_name: client
   ports:
    - "8080:8080"
volumes:
  db_data:
